// Command refresh-spx-members pulls the current S&P-500 constituent list from
// Wikipedia's "List of S&P 500 companies" article and rewrites
// internal/breadth/spx/members_data.go with the result. Runs as a
// developer tool — the daemon itself ALSO scrapes Wikipedia at runtime
// (internal/breadth/spx/refresh.go) using the same shared parser, so
// this script and the daemon land on identical bytes for identical
// inputs. Single source of truth for the parse logic lives at
// internal/breadth/spx/wikipedia.go.
//
// Invoked by `make refresh-spx-members` and `make release`. The
// release flow fails-closed if the rewrite produces a diff: the
// maintainer commits the membership update separately, then re-runs
// the release. This keeps the binary's checked-in member list in
// lockstep with the git tag.
//
// Sanity bounds: refuses to write if fewer than MinMembers or more
// than MaxMembers tickers are extracted (Wikipedia table structure
// breakage would otherwise silently corrupt the list). The S&P 500
// actually carries ~500–505 names with the dual-class entries (BRK.B,
// GOOG/GOOGL, etc.); the band is intentionally wider than that to
// absorb transient mid-rebalance editing on the source page.
package main

import (
	"context"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strings"
	"time"

	"github.com/osauer/canary/v2/internal/breadth/spx"
)

const outputPath = "internal/breadth/spx/members_data.go"

func main() {
	dry := flag.Bool("dry-run", false, "parse and print the symbols but don't rewrite members_data.go")
	urlOverride := flag.String("url", "", "override Wikipedia URL (for testing against a fixture HTTP server)")
	flag.Parse()

	url := spx.WikipediaURL
	if *urlOverride != "" {
		url = *urlOverride
	}

	// 30s ceiling so a hung connection doesn't stall a release
	// indefinitely. The shared client inside FetchAndParse uses 15s
	// per-request — this ctx is the belt over the suspenders.
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	symbols, asOf, err := spx.FetchAndParse(ctx, url, "refresh-spx-members/1.0")
	if err != nil {
		log.Fatalf("fetch/parse %s: %v", url, err)
	}
	if n := len(symbols); n < spx.MinMembers || n > spx.MaxMembers {
		log.Fatalf("sanity check: parsed %d symbols, want %d-%d (Wikipedia table structure may have changed)", n, spx.MinMembers, spx.MaxMembers)
	}

	if *dry {
		for _, s := range symbols {
			fmt.Println(s)
		}
		fmt.Fprintf(os.Stderr, "\n%d symbols (would write to %s)\n", len(symbols), outputPath)
		return
	}

	// The file records a membership list; asOf is metadata about that list.
	// asOf moves with the calendar, so rewriting on every run made the output
	// differ whenever the day had changed even though membership had not — and
	// the release aborts on any diff here, so a cut on a later day than the last
	// refresh failed on a timestamp carrying no information. Leaving the file
	// alone when the symbol set is unchanged is what the render function's own
	// contract already claims: re-running when nothing has changed leaves the
	// tree clean.
	if current, _ := spx.MemberList(); slices.Equal(current, symbols) {
		fmt.Fprintf(os.Stderr, "Membership unchanged (%d symbols); leaving %s and its as-of stamp alone\n", len(symbols), outputPath)
		return
	}

	src, err := renderMembersData(symbols, asOf)
	if err != nil {
		log.Fatalf("render members_data.go: %v", err)
	}
	if err := os.WriteFile(outputPath, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", outputPath, err)
	}
	fmt.Fprintf(os.Stderr, "Wrote %d symbols to %s (as-of %s)\n", len(symbols), outputPath, asOf.Format("2006-01-02"))
}

// renderMembersData formats the symbols + as-of timestamp into a
// gofmt-clean Go source file. Deterministic: same inputs always
// produce byte-identical output, so re-running the script when
// nothing's changed leaves the working tree clean.
func renderMembersData(symbols []string, asOf time.Time) ([]byte, error) {
	var b strings.Builder
	b.WriteString(`// Code generated by scripts/refresh-spx-members. DO NOT EDIT BY HAND.
//
// To refresh: ` + "`make refresh-spx-members`" + `. The release flow runs this
// automatically; manual edits will be overwritten on the next release.

package spx

import "time"

// sp500AsOf is the timestamp at which this list was last regenerated
// from Wikipedia's "List of S&P 500 companies" article. The
// verification scrape compares against $SPXA50R daily, so drift here
// shows up as a divergence in verify.log within one trading day of any
// reconstitution.
var sp500AsOf = time.Date(`)
	fmt.Fprintf(&b, "%d, time.%s, %d, 0, 0, 0, 0, time.UTC)\n", asOf.Year(), asOf.Month().String(), asOf.Day())
	b.WriteString(`
// sp500Members is the S&P-500 constituent list pulled from Wikipedia
// and rewritten by ` + "`make refresh-spx-members`" + ` on every release.
var sp500Members = []string{
`)
	for _, s := range symbols {
		fmt.Fprintf(&b, "\t%q,\n", s)
	}
	b.WriteString("}\n")

	// gofmt the result so the checked-in file matches `make fmt`'s
	// idea of canonical formatting. Skipping this means every release
	// would dirty the working tree with cosmetic whitespace edits.
	return format.Source([]byte(b.String()))
}
