

const state = {
  snapshot: null,
  reconciliationCheck: { busy: false, state: "", error: false },
  safeNotificationTest: { busy: false, state: "", error: false },
  alertSettings: { mode: "watch_and_act" },
  alertSettingsUpdate: { busy: false, state: "", error: false },
  alerts: null,
  alertsFeedValid: null,
  alertsFeedError: "",
  alertsRefreshInFlight: null,
  alertsRefreshTimer: null,
  alertsRefreshDueAt: 0,
  alertsRefreshTimerEnsureTrailing: false,
  alertsRefreshAfterFlight: false,
  alertsLastRefreshAt: 0,
  alertsFetchDeadlineMs: null,
  renderedAlertAttention: null,
  attentionEpoch: 0,
  attentionReadInFlight: null,
  attentionRetryTimer: null,
  attentionStatus: { state: "", error: false },
  pushInspection: { state: "status unavailable", busy: false },
  vapidPublicKey: "",
  eventSource: null,
  reconnectTimer: null,
  connectionText: "Connecting",
  connectionOK: false,
  pairingRequired: false,
  authenticated: false,
  accountValueVisible: localStorage.getItem("canaryAccountValueVisible") === "true",
  stressDetailOpen: false,
  rulesDetailOpen: false,
  regimeDetailOpen: false,
  regimeStressExpansionInitialized: false,
  detailPreferenceSet: false,
  accountOverviewOpen: false,
  underlyingDetailOpen: false,
  portfolioDetailOpen: false,
  accountExposureOpen: false,
  protectionOpen: false,
  opportunitiesOpen: false,
  selectedMarket: localStorage.getItem("canarySelectedMarket") || "us",
  marketCalendarOverride: null,
  proposalMarketCalendars: {},
  proposalMarketCalendarBusy: {},
  ordersOpen: null,
  openOrderEdits: {},
  strategyDrafts: {},
  strategyPreviewBusy: "",
  strategyPreviews: {},
  strategySubmitBusy: "",
  strategySubmits: {},
  protectionPreviewBusy: "",
  protectionPreviews: {},
  protectionSubmitBusy: "",
  protectionSubmits: {},
  protectionSnapshotBusy: false,
  protectionSnapshotLastAt: 0,
  protectionSnapshotNotice: "",
  protectionQuoteTicks: {},
  protectionQtyOverrides: {},
  protectionDerisk: { percent: 25, busy: "", result: null, submitted: null, requestRef: "", previewedAt: 0, abort: null },
  opportunityPreviewBusy: "",
  opportunityPreviews: {},
  opportunitySubmitBusy: "",
  opportunitySubmits: {},
  opportunitySnapshotBusy: false,
  opportunitySnapshotLastAt: 0,
  opportunitySnapshotNotice: "",
	underlyingNotice: "",
  fallbackRefreshBusy: false,
  settings: null,
  activeTab: normalizedTab(localStorage.getItem("canaryActiveTab") || "monitor"),
};

function normalizedTab(tab) {
  if (tab === "brief" || tab === "alerts" || tab === "orders" || tab === "settings") return tab;
  return "monitor";
}

export { normalizedTab, state };
