// Command edge-flex emits the Canary reporting Flex-query reference from the
// parser's canonical manifest. The command and output URL retain their
// historical names for compatibility. The same manifest drives runtime
// diagnostics and setup payloads, so the app, CLI, MCP, and documentation
// cannot acquire separate field lists.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/osauer/canary/v2/internal/flexstmt"
)

const defaultOutput = "docs/docs/reference/edge-flex.md"

func main() {
	output := flag.String("o", defaultOutput, "output path (- for stdout)")
	flag.Parse()
	body := render()
	if *output == "-" {
		_, _ = os.Stdout.WriteString(body)
		return
	}
	if err := os.WriteFile(*output, []byte(body), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
}

func render() string {
	out := &strings.Builder{}
	out.WriteString("# Canary reporting Flex query\n\n")
	out.WriteString("*Generated by `scripts/docgen/edge-flex` from `internal/flexstmt.CanonicalQueryManifest`. Do not edit by hand. Run `make docs-regen` after changing the manifest.*\n\n")
	out.WriteString("Canary needs one XML Activity Flex Query for reconciliation, statement-derived equity, and Edge. The consumers share the existing `[flex]` query ID and token contract. The query profile version is `")
	out.WriteString(flexstmt.ManifestVersion)
	out.WriteString("`. Follow [Set up broker reporting](../start/reporting.md) for the screenshot-driven Client Portal workflow and secure activation.\n\n")

	out.WriteString("## Setup\n\n")
	for i, step := range flexstmt.SetupSteps() {
		fmt.Fprintf(out, "%d. %s\n", i+1, step)
	}
	out.WriteString("\nWhen a non-empty section proves that a required field is absent, reporting diagnostics name only the stable field key. An absent or empty section remains `unproved`: IBKR may omit empty containers, so no rows means its XML cannot prove which fields were selected.\n\n")

	out.WriteString("## Required sections and fields\n\n")
	for _, section := range flexstmt.CanonicalQueryManifest() {
		fmt.Fprintf(out, "### %s\n\n", section.Label)
		fmt.Fprintf(out, "XML `%s > %s`", section.Container, section.Row)
		if section.LevelOfDetail != "" {
			fmt.Fprintf(out, "; level of detail `%s`", section.LevelOfDetail)
		}
		out.WriteString(".\n\n")
		for _, field := range section.RequiredFields {
			fmt.Fprintf(out, "- `%s`\n", field)
		}
		out.WriteString("\n")
	}
	out.WriteString("## Optional currency conversion rates\n\n")
	out.WriteString("Some Client Portal account and interface variants offer a `Currency Conversion Rate` section; others do not. When it is available, selecting all four fields (`dateTime`, `fromCurrency`, `toCurrency`, and `rate`) gives Edge dated broker FX evidence for non-base-currency horizons. Its XML shape is `ConversionRates > ConversionRate`. It is optional and its absence never blocks reporting setup. `Forex Balances` and `Forex P/L Details` are different reports and are not substitutes. Rows that still lack enough broker-stated FX evidence remain unscored with a typed reason.\n\n")

	out.WriteString("## Retrieval and evidence\n\n")
	out.WriteString("The ordinary daily report refreshes the trailing 35 days. Edge additionally requests four paced, resumable ranges covering the inclusive trailing 365 days and revalidates the full year monthly. Every complete active-query XML response is retained as the original broker evidence; SQLite holds the typed current projection and immutable record versions. Candidate validation parses XML only in memory and discards it.\n\n")
	out.WriteString("A backfill chunk advances only when the returned statement range fully contains the requested inclusive range. A shorter or stale broker response is retained as evidence but retried; it cannot mark the full-year revalidation complete.\n\n")
	out.WriteString("Reading `canary reporting status`, `canary_reporting`, `canary edge`, `canary_edge`, or `/api/edge` never starts a Flex or market-data request. Only the explicit setup validation or background acquisition lane contacts Flex. Background work publishes a new fingerprinted snapshot atomically after the evidence and exact-ConID daily bars have been processed.\n\n")
	out.WriteString("## Safety and scope\n\n")
	out.WriteString("Broker reporting and Edge are read-only. Public results contain fingerprints and typed requirements, not account IDs, Flex query IDs, tokens, order or execution IDs, statement filenames, file paths, raw XML, or broker free text. Decision price impact is a fixed price-path comparison, not generic P/L, causality, predictive skill, or investment advice. See [Canary Edge](../understand/edge.md) for the calculation and limitations.\n")
	return out.String()
}
