// Command cli-ref emits docs/docs/reference/cli.md from the CLI command
// registry. Source of truth is the Go code: cli.Catalog() carries the name,
// summary, usage line, flags, subcommands, guard class, and terminal-app
// support of every subcommand, and mcp.ExcludedCLI carries the recorded
// reason a command has no MCP tool counterpart.
//
// Invoked by `make docs-regen` (writes the file) and `make docs-check`
// (writes to a tempfile, diffs against the checked-in copy, fails CI if they
// drift). The convention is: change the registry, regenerate, commit both in
// the same patch.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/osauer/canary/v2/internal/cli"
	"github.com/osauer/canary/v2/internal/mcp"
)

const defaultOutput = "docs/docs/reference/cli.md"

// commandNotes carries the framing the registry cannot express. A command
// that can reach the broker must not read like an ordinary lookup on a public
// page, and a guard class on its own does not say that.
var commandNotes = map[string]string{
	"order": "`status` reads one journaled order and `preview` mints a tokenized draft: it runs the broker WhatIf and never transmits, and a minted token is not submit eligibility. " +
		"`place`, `modify`, and `cancel` are broker writes: each requires an explicit human instruction for that exact order, and place/modify additionally consume a submit-eligible preview token through the daemon's ordinary admission gates (mode and account pins, caps, freeze, origin, journal). " +
		"The constrained proposal and opportunity surfaces remain the daemon-authored candidate paths; this family is the operator's direct gated path.",
	"purge": "`canary purge SYMBOL`, `canary purge --all`, and `purge execute` close live positions through the broker. " +
		"They carry the same gate as `canary order`: an explicit human instruction for that exact action, in that moment. " +
		"`dry-run`, `status`, and `monitor` only read.",
	"proposals": "Protection proposals are advisory. The daemon can propose a close or a reduce, and only `submit` and `reduce` reach the broker. " +
		"Each needs an explicit human instruction for that exact order.",
	"opportunities": "Opportunity detection is advisory. Only `exercise` reaches the broker, and it needs an explicit human instruction for that exact action.",
	"trading":       "`status` reads the local trading gate and its blockers.",
	"stop": "Stopping is local process management: it signals the daemon and the app on this machine and reaches no broker. Orders already working stay at the broker, but nothing local watches them until the daemon runs again — no fills or cancels in the journal, no protection proposals, no phone alerts. " +
		"So `stop` asks before it stops a daemon that still has work in flight, the same work its own idle shutdown defers on, and `--yes` is how a script answers. " +
		"`--force` only escalates a stuck process from SIGTERM to SIGKILL after `--timeout`; it never widens what is stopped. " +
		"MCP servers belong to the AI client that started them and are reported, never signalled.",
	"settings": "`show` reads. `set` writes a runtime preference, and the write path has its own gate: `trading.freeze` and the trading-limit keys are accepted only from an interactive human terminal, and agent and paired-device origins are rejected. " +
		"The keys are listed in the [configuration reference](config.md).",
}

func main() {
	output := flag.String("o", defaultOutput, "output path (- for stdout)")
	flag.Parse()

	body := render(cli.Catalog())

	if *output == "-" {
		os.Stdout.WriteString(body)
		return
	}
	if err := os.WriteFile(*output, []byte(body), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
}

// render produces the full markdown body for the command registry. Registry
// order is preserved throughout: it is the order of the help table, and it
// keeps `status` first.
func render(specs []cli.CommandSpec) string {
	out := &strings.Builder{}
	out.WriteString("# CLI reference\n\n")
	out.WriteString("*Generated by `scripts/docgen/cli-ref`. Do not edit by hand. Run `make docs-regen` after changing `internal/cli/cli.go` or `internal/cli/catalog.go`.*\n\n")

	fmt.Fprintf(out, "`canary` is one binary with %d subcommands, listed here in registry order. ", len(specs))
	out.WriteString("`canary status` comes first on purpose: when anything else fails, it is the command that says whether the daemon is running and the gateway is reachable. ")
	out.WriteString("Running `canary` with no arguments prints the grouped command summary.\n\n")

	out.WriteString("Add `--json` to a data command for machine-readable output instead of a table. ")
	out.WriteString("Commands that accept `--watch` redraw on an interval set by `--rate`, as in `canary account --watch --rate 1s`. ")
	out.WriteString("Color is on for terminals and off for pipes; `NO_COLOR=1` turns it off, and `CANARY_COLOR=always` or `CANARY_COLOR=never` forces it either way.\n\n")

	out.WriteString("The flag tables below come from the shared command catalog. ")
	out.WriteString("Run `canary <command> --help` for the flags a command parses today, with their help text. That output is the authority if the two ever disagree.\n\n")

	out.WriteString("The guard column says what a command does: `read-only` reads and prints, `local` writes local setup or configuration state, and `confirm` reaches something a human has to decide first. ")
	out.WriteString("Where subcommands carry different guards, the summary shows the strictest one and the command's own section lists the split. ")
	out.WriteString("The guard is documentation of behavior, not the mechanism that enforces it. The real gates live in the CLI. ")
	out.WriteString("Standard builds have no broker-write path compiled in at all. The separate trading build adds one, and it still requires a verified gateway session, a submit-eligible preview token where one applies, a local journal entry, daemon authorization, and `trading.freeze` set to false. ")
	out.WriteString("Nothing on this page grants any of that.\n\n")

	out.WriteString("The group column is the heading a command appears under in `canary --help`: Desk is the account, its positions, orders and risk; Markets is named-symbol technical evidence; System is running Canary itself. ")
	out.WriteString("It is a reading aid for a long command list and says nothing about what a command may do — that is the guard.\n\n")

	out.WriteString("## Command summary\n\n")
	out.WriteString("| Command | Group | Summary | Guard | MCP tool |\n")
	out.WriteString("|---------|-------|---------|-------|----------|\n")
	for _, spec := range specs {
		counterpart := "yes"
		if _, cliOnly := mcp.ExcludedCLI[spec.Name]; cliOnly {
			counterpart = "CLI only"
		}
		fmt.Fprintf(out, "| [`canary %s`](#canary-%s) | %s | %s | `%s` | %s |\n",
			spec.Name, spec.Name, groupTitle(spec.Group), escapeTable(spec.Summary), strictestGuard(spec), counterpart)
	}
	out.WriteString("\n")

	for _, spec := range specs {
		renderCommand(out, spec)
	}
	return strings.TrimRight(out.String(), "\n") + "\n"
}

// renderCommand emits one command section: summary, safety framing where the
// command can reach the broker, guard and MCP status, usage, subcommands,
// and flags.
func renderCommand(out *strings.Builder, spec cli.CommandSpec) {
	fmt.Fprintf(out, "## `canary %s`\n\n", spec.Name)
	fmt.Fprintf(out, "%s.\n\n", strings.TrimRight(spec.Summary, "."))

	if note := commandNotes[spec.Name]; note != "" {
		fmt.Fprintf(out, "%s\n\n", note)
	}

	fmt.Fprintf(out, "Guard `%s`", spec.Guard)
	if strict := strictestGuard(spec); strict != spec.Guard {
		fmt.Fprintf(out, ", with `%s` subcommands", strict)
	}
	out.WriteString(". ")
	if reason, cliOnly := mcp.ExcludedCLI[spec.Name]; cliOnly {
		fmt.Fprintf(out, "CLI only, with no MCP tool: %s.\n\n", strings.TrimRight(reason, "."))
	} else {
		out.WriteString("Also available as an MCP tool.\n\n")
	}

	if spec.Usage != "" {
		// Usage strings separate alternative invocations with " | ". One
		// alternative per line keeps the long ones readable; enum values such
		// as `us|de` carry no spaces and are left alone.
		fmt.Fprintf(out, "```text\n%s\n```\n\n", strings.ReplaceAll(spec.Usage, " | ", "\n"))
	}

	renderSubcommands(out, spec)

	if len(spec.Flags) == 0 {
		fmt.Fprintf(out, "*The catalog records no flags. Run `canary %s --help` for what the command parses.*\n\n", spec.Name)
		return
	}
	out.WriteString("**Flags**\n\n")
	out.WriteString("| Flag | Takes a value | Allowed values |\n")
	out.WriteString("|------|---------------|----------------|\n")
	for _, f := range spec.Flags {
		takes := "no"
		if f.TakesValue {
			takes = "yes"
		}
		values := "-"
		if len(f.Values) > 0 {
			quoted := make([]string, len(f.Values))
			for i, v := range f.Values {
				quoted[i] = "`" + v + "`"
			}
			values = strings.Join(quoted, ", ")
		}
		fmt.Fprintf(out, "| `--%s` | %s | %s |\n", f.Name, takes, values)
	}
	out.WriteString("\n")
}

// renderSubcommands lists the nested command words. The per-subcommand guard
// column only appears when the subcommands disagree with each other; a uniform
// set is already covered by the command's own guard line.
func renderSubcommands(out *strings.Builder, spec cli.CommandSpec) {
	if len(spec.Subcommands) == 0 {
		return
	}
	uniform := true
	for _, sub := range spec.Subcommands[1:] {
		if sub.Guard != spec.Subcommands[0].Guard {
			uniform = false
			break
		}
	}
	if uniform {
		names := make([]string, len(spec.Subcommands))
		for i, sub := range spec.Subcommands {
			names[i] = "`" + sub.Name + "`"
		}
		fmt.Fprintf(out, "Subcommands: %s.\n\n", strings.Join(names, ", "))
		return
	}
	out.WriteString("**Subcommands**\n\n")
	out.WriteString("| Subcommand | Guard |\n")
	out.WriteString("|------------|-------|\n")
	for _, sub := range spec.Subcommands {
		fmt.Fprintf(out, "| `%s` | `%s` |\n", sub.Name, sub.Guard)
	}
	out.WriteString("\n")
}

// guardRank orders the guard classes from least to most restrictive. A
// command whose own guard is read-only can still own a confirm subcommand,
// so the summary reports the strictest reachable class rather than the
// command's own.
var guardRank = map[cli.GuardClass]int{
	cli.GuardReadOnly: 0,
	cli.GuardLocal:    1,
	cli.GuardConfirm:  2,
}

// groupTitle renders a help group the way the terminal listing heads it.
func groupTitle(group cli.HelpGroup) string {
	for _, spec := range cli.HelpGroups() {
		if spec.Group == group {
			return spec.Title
		}
	}
	return string(group)
}

func strictestGuard(spec cli.CommandSpec) cli.GuardClass {
	strictest := spec.Guard
	for _, sub := range spec.Subcommands {
		if guardRank[sub.Guard] > guardRank[strictest] {
			strictest = sub.Guard
		}
	}
	return strictest
}

// escapeTable escapes characters that would break a markdown table row.
func escapeTable(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
